mport java.util.concurrent.Semaphore;i
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;
import java.util.*;

public class Project2
{
	class  sharedSynchronizationData
		{
		public Semaphore patients;
		public Semaphore receptionist;
		public Semaphore nurses;
		public int maxPatients;	
		public int numPatients = 0;
		public Lock mutex;       	
		public int patId;
		public Queue<Integer>	pQueue;
		public Lock mutex2;			
		public int pRegistered;
		public int numNurses;
		public int numDoctors;

sharedSynchronizationData(int num)
																														{
																																	// Create semaphores and a lock
																																	// 			patients		=	new Semaphore(0);
																																	// 						receptionist	=	new Semaphore(0);
																																	// 									nurses			=	new Semaphore(0);
																																	// 												mutex			=	new ReentrantLock();
																																	// 															mutex2			=	new ReentrantLock();
																																	// 																		maxPatients		=	num;
																																	// 																					pQueue			=	new LinkedList<Integer>();
																																	// 																								pRegistered		=	0;
																																	// 																										}
																																	// 																											}
																																	//
																																	// 																												class Receptionist extends Thread
																																	// 																													{
																																	// 																															boolean busy;
																																	// 																																	sharedSynchronizationData  synch;
																																	//
																																	// 																																			public Receptionist( sharedSynchronizationData s )
																																	// 																																					{
																																	// 																																								busy = false;
																																	// 																																											synch = s;
																																	// 																																													}
																																	//
																																	// 																																															public void run()
																																	// 																																																	{
																																	// 																																																				for (int i = 0; i<synch.numPatients; i++)
																																	// 																																																							{
																																	// 																																																											try
																																	// 																																																															{
																																	// 																																																																				synch.patients.acquire();        // Wait if # of patients is zero
																																	// 																																																																								}
																																	// 																																																																												catch (InterruptedException e){}
																																	//
																																	// 																																																																																// We have at least one patient at this point.
																																	// 																																																																																				synch.mutex.lock();      			// protect "numPatients"
																																	// 																																																																																								synch.maxPatients++;         		// a patient moves to the receptionist
																																	// 																																																																																												synch.receptionist.release();       // the receptionist is ready to register
																																	// 																																																																																																synch.mutex.unlock();
																																	//
																																	// 																																																																																																				try
																																	// 																																																																																																								{
																																	// 																																																																																																													Thread.sleep(20);
																																	// 																																																																																																																	}
																																	// 																																																																																																																					catch (InterruptedException e){}
																																	//
																																	// 																																																																																																																								//	System.out.println("Receptionist registers patient " + i);
																																	// 																																																																																																																											}
																																	// 																																																																																																																													}
																																	// 																																																																																																																														}
																																	//
																																	// 																																																																																																																															class Patient extends Thread
																																	// 																																																																																																																																{
																																	// 																																																																																																																																		int id;
																																	// 																																																																																																																																				boolean isWaiting;
																																	// 																																																																																																																																						sharedSynchronizationData  synch;
																																	//
																																	// 																																																																																																																																								public Patient(int num, sharedSynchronizationData  s)
																																	// 																																																																																																																																										{
																																	// 																																																																																																																																													id = num;
																																	// 																																																																																																																																																isWaiting = false;
																																	// 																																																																																																																																																			synch = s;
																																	// 																																																																																																																																																					}
																																	//
																																	// 																																																																																																																																																							public void  run()
																																	// 																																																																																																																																																									{
																																	// 																																																																																																																																																												System.out.println("Patient " + id + " enters waiting room, waits for receptionist.");
																																	// 																																																																																																																																																															synch.mutex.lock();        				// obtain lock for access of "numPatients"
																																	//
																																	// 																																																																																																																																																																		if (synch.maxPatients > 0)
																																	// 																																																																																																																																																																					{
																																	// 																																																																																																																																																																									--synch.maxPatients;      			// a patients is waiting
																																	//
																																	// 																																																																																																																																																																													// There are free spots for patients.
																																	// 																																																																																																																																																																																	synch.patients.release();      		// wake up the receptionist (if necessary)
																																	//
																																	// 																																																																																																																																																																																					synch.mutex.unlock();    			// "numPatients" is no longer accessed
																																	// 																																																																																																																																																																																									try
																																	// 																																																																																																																																																																																													{
																																	// 																																																																																																																																																																																																		synch.receptionist.acquire();	// wait for my turn
																																	// 																																																																																																																																																																																																						}
																																	// 																																																																																																																																																																																																										catch (InterruptedException e){}
																																	// 																																																																																																																																																																																																														System.out.println("Receptionist registers patient " + id);
																																	// 																																																																																																																																																																																																																		try
																																	// 																																																																																																																																																																																																																						{
																																	// 																																																																																																																																																																																																																											Thread.sleep(20);
																																	// 																																																																																																																																																																																																																															}
																																	// 																																																																																																																																																																																																																																			catch (InterruptedException e){}
																																	//
																																	// 																																																																																																																																																																																																																																							System.out.println("Patient " + id + " leaves receptionist and sits in waiting room");
																																	// 																																																																																																																																																																																																																																											synch.pRegistered ++;
																																	// 																																																																																																																																																																																																																																															synch.pQueue.add(id);
																																	// 																																																																																																																																																																																																																																																			isWaiting = true;
																																	// 																																																																																																																																																																																																																																																						}
																																	// 																																																																																																																																																																																																																																																									Thread.currentThread().stop();
																																	// 																																																																																																																																																																																																																																																											}
																																	// 																																																																																																																																																																																																																																																												}
																																	//
																																	// 																																																																																																																																																																																																																																																													class Nurse extends Thread
																																	// 																																																																																																																																																																																																																																																														{
																																	// 																																																																																																																																																																																																																																																																int id;
																																	// 																																																																																																																																																																																																																																																																		boolean isBusy;
																																	// 																																																																																																																																																																																																																																																																				sharedSynchronizationData  synch;
																																	//
																																	// 																																																																																																																																																																																																																																																																						public Nurse(int num, sharedSynchronizationData  s)
																																	// 																																																																																																																																																																																																																																																																								{
																																	// 																																																																																																																																																																																																																																																																											id = num;
																																	// 																																																																																																																																																																																																																																																																														isBusy = false;
																																	// 																																																																																																																																																																																																																																																																																	synch = s;
																																	// 																																																																																																																																																																																																																																																																																			}
																																	//
																																	// 																																																																																																																																																																																																																																																																																					public void  run()
																																	// 																																																																																																																																																																																																																																																																																							{
																																	// 																																																																																																																																																																																																																																																																																										synch.mutex2.lock();        				// obtain lock for access of "pQueue"
																																	//
																																	// 																																																																																																																																																																																																																																																																																													if (!synch.pQueue.isEmpty())
																																	// 																																																																																																																																																																																																																																																																																																{
																																	// 																																																																																																																																																																																																																																																																																																				Integer patientId = synch.pQueue.remove();
																																	// 																																																																																																																																																																																																																																																																																																								--synch.pRegistered;
																																	//
																																	// 																																																																																																																																																																																																																																																																																																												synch.mutex2.unlock();    			// "pQueue" is no longer accessed
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																try
																																	// 																																																																																																																																																																																																																																																																																																																				{
																																	// 																																																																																																																																																																																																																																																																																																																									Thread.sleep(20);
																																	// 																																																																																																																																																																																																																																																																																																																													}
																																	// 																																																																																																																																																																																																																																																																																																																																	catch (InterruptedException e){}
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																																					System.out.println("Nurse " + id + " takes patient " + patientId + " to doctor's office");
																																	// 																																																																																																																																																																																																																																																																																																																																									isBusy = true;
																																	// 																																																																																																																																																																																																																																																																																																																																												}
																																	// 																																																																																																																																																																																																																																																																																																																																															Thread.currentThread().stop();
																																	// 																																																																																																																																																																																																																																																																																																																																																	}
																																	// 																																																																																																																																																																																																																																																																																																																																																		}
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																																																			public void simulate(int numP, int numN, int numD)
																																	// 																																																																																																																																																																																																																																																																																																																																																				{
																																	// 																																																																																																																																																																																																																																																																																																																																																						// Make synchronization data to be shared
																																	// 																																																																																																																																																																																																																																																																																																																																																								sharedSynchronizationData  synch = new sharedSynchronizationData(15);
																																	// 																																																																																																																																																																																																																																																																																																																																																										synch.numPatients = numP;
																																	// 																																																																																																																																																																																																																																																																																																																																																												synch.numNurses = numN;
																																	// 																																																																																																																																																																																																																																																																																																																																																														synch.numDoctors = numD;
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																																																																Thread recpThread;
																																	// 																																																																																																																																																																																																																																																																																																																																																																		Thread[] patThread = new Thread[synch.numPatients];
																																	// 																																																																																																																																																																																																																																																																																																																																																																				Thread[] nurThread = new Thread[synch.numNurses];
																																	// 																																																																																																																																																																																																																																																																																																																																																																						int  i;
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																																																																								// Make the receptionist Thread
																																	// 																																																																																																																																																																																																																																																																																																																																																																										recpThread = new Receptionist(synch);
																																	// 																																																																																																																																																																																																																																																																																																																																																																												recpThread.start();
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																																																																														// Make the patient Threads
																																	// 																																																																																																																																																																																																																																																																																																																																																																																for (i = 0; i < synch.numPatients; i++)
																																	// 																																																																																																																																																																																																																																																																																																																																																																																		{
																																	// 																																																																																																																																																																																																																																																																																																																																																																																					try
																																	// 																																																																																																																																																																																																																																																																																																																																																																																								{
																																	// 																																																																																																																																																																																																																																																																																																																																																																																												Thread.sleep(10);
																																	// 																																																																																																																																																																																																																																																																																																																																																																																															}
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																		catch (InterruptedException e){}
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																					patThread[i] = new Patient(i, synch);
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								patThread[i].start();
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    	}
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    			int j = synch.numPatients;
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    					while(j>0)
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    							{
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    	for (i = 0; i < synch.numNurses; i++)
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    				{
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    								try
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    												{
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																	Thread.sleep(10);
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																					}
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																									catch (InterruptedException e){}
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																													nurThread[i] = new Nurse(i, synch);
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																	nurThread[i].start();
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																				}
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																							j -= 5;
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																									}
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																											// close all threads
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																													try
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																															{
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																		recpThread.join();
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																				}
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						catch (InterruptedException e){}
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    	for( i = 0; i < synch.numPatients; ++i )
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    			{
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    						try
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    									{
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    													patThread[i].join();
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																}
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																			catch (InterruptedException e){}
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																					}
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																						}
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																							public static void main(String args[])
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																								{
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																										int numP = 5, numN = 5, numD = 5;
																																	//
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																												Project2 clinic;
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																														clinic = new Project2();
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																																clinic.simulate(numP, numN, numD);
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																																	}
																																	// 																																																																																																																																																																																																																																																																																																																																																																																																								    								    																																																						    																																																																//
